Iter5
mcrgnt/yp1 pull request #5
Opened 2024-05-08 06:12 UTC by mcrgnt

Iter5 pr

2024-05-10 14:00 UTC, s-shpak commented on cmd/agent/agent.go
> +func (t *Agent) paramsParseEnv() error {
Не стоит мешать несколько структур друг с другом. Вынеси конфигурационные параметры в отдельную структуру

2024-05-10 14:03 UTC, s-shpak commented on cmd/agent/agent.go
> +	err = agent.paramsParseEnv()
Не стоит вызывать несколько разных функций для парсинга конфигурации на этом уровне. Инкапсулируй это в одну функцию

2024-05-10 14:03 UTC, s-shpak commented on cmd/agent/agent.go
> +	go metrics.ReportMetrics(&metrics.ReportMetricsParams{
Горутины в этом спринте не нужны

2024-05-10 14:04 UTC, s-shpak commented on cmd/agent/agent.go
> +		ctx: logger.NewLoggerContext(ctx, &logger.LoggerInitParams{
В Go так не делают. 1. Контекст никогда не хранится в функции 2. лучше передавать логгер и хранить его отдельно

2024-05-10 14:05 UTC, s-shpak commented on cmd/agent/agent.go
> +func NewAgent(ctx context.Context) (agent *Agent, err error) {
Именованные возвращаемые значения здесь (и в общем случае) не нужны

2024-05-10 14:06 UTC, s-shpak commented on go.mod
> +	github.com/caarlos0/env/v10 v10.0.0
Есть 11-ая версия

2024-05-10 14:06 UTC, s-shpak commented on internal/api/api.go
> +			Version:        "v-",
Это дублирование константы ?

2024-05-10 14:07 UTC, s-shpak commented on internal/api/handler.go
> +	w.Write([]byte(fmt.Sprintf("%v", updateParams.Value)))
Используй `strconv` для перевода чисел в строки

2024-05-10 14:07 UTC, s-shpak commented on internal/api/handler_test.go
> +// func TestDefaultHandler_handleUpdate(t *testing.T) {
Это deadcode ?

2024-05-10 14:08 UTC, s-shpak commented on internal/metrics/metrics.go
> +	val := reflect.ValueOf(memStats).Elem()
Не используй рефлексию, это дорого

2024-05-10 14:09 UTC, s-shpak commented on internal/metrics/metrics_test.go
> +			if gotMetricsNamesList := getFullMetricsNamesList(); !reflect.DeepEqual(gotMetricsNamesList, tt.wantMetricsNamesList) {
Не очень понимаю зачем нужен этот тест. Какая разница, как инициализирован список, если сервер ведет себя согласно спецификации ?

2024-05-10 14:12 UTC, s-shpak commented on internal/metrics/metrics.go
> +		PollMetricsInc.Add(1)
Этот параметр никогда не сбарсывается ? Что если клиент будет перезапущен ? Будет ли на сервере сохранено корректное количество сбора метрик ?

2024-05-13 12:39 UTC, mcrgnt commented on cmd/agent/main.go
> +		panic(err)
это как раз тот случай где можно

2024-05-13 12:40 UTC, mcrgnt commented on cmd/agent/main.go
> +	ctx, _ := signal.NotifyContext(context.Background(), os.Interrupt)
не считаю что это лишнее

2024-05-13 13:39 UTC, mcrgnt commented on cmd/agent/agent.go
> +func (t *Agent) paramsParseEnv() error {
+

2024-05-13 13:40 UTC, mcrgnt commented on cmd/agent/agent.go
> +	err = agent.paramsParseEnv()
+

2024-05-13 13:40 UTC, mcrgnt commented on cmd/agent/agent.go
> +	go metrics.ReportMetrics(&metrics.ReportMetricsParams{
+

2024-05-13 13:43 UTC, mcrgnt commented on cmd/agent/agent.go
> +		ctx: logger.NewLoggerContext(ctx, &logger.LoggerInitParams{
непонятно

2024-05-13 13:43 UTC, mcrgnt commented on go.mod
> +	github.com/caarlos0/env/v10 v10.0.0
+

2024-05-13 13:43 UTC, mcrgnt commented on internal/api/api.go
> +			Version:        "v-",
+

2024-05-13 14:23 UTC, mcrgnt commented on internal/api/handler.go
> +	w.Write([]byte(fmt.Sprintf("%v", updateParams.Value)))
+

2024-05-13 14:41 UTC, mcrgnt commented on internal/metrics/metrics_test.go
> +			if gotMetricsNamesList := getFullMetricsNamesList(); !reflect.DeepEqual(gotMetricsNamesList, tt.wantMetricsNamesList) {
+

2024-05-14 22:39 UTC, mcrgnt commented on internal/metrics/metrics.go
> +	val := reflect.ValueOf(memStats).Elem()
ok

2024-05-14 22:39 UTC, mcrgnt commented on internal/metrics/metrics.go
> +		PollMetricsInc.Add(1)
fixed

2024-05-14 22:43 UTC, mcrgnt commented on cmd/agent/agent.go
> +		ctx: logger.NewLoggerContext(ctx, &logger.LoggerInitParams{
Сначала решил поменять логгер. Выбрал из топ 1-й по дзен (zerolog). И увидел вот такое ))
https://github.com/rs/zerolog/blob/147ae653507db96d498366e368f715f4da23bf25/log.go#L236C1-L236C25
Так что оставил пока как есть.

2024-05-15 06:56 UTC, mcrgnt commented on cmd/agent/main.go
> +		panic(err)
ok

2024-05-16 11:05 UTC, s-shpak commented on cmd/agent/agent.go
> +		ctx: logger.NewLoggerContext(ctx, &logger.LoggerInitParams{
См. официальную рекомендацию: https://go.dev/blog/context-and-structs

Все что не запрещено компилятором можно использовать. Некоторые практики, тем не менее, считаются плохими. Ты можешь использовать свой логгер для логгирования, но не можешь в качестве контекста.

Кроме того на втором спринте есть требование использовать стандартный логгер, потому тебе все равно придется его заменить

2024-05-16 11:13 UTC, s-shpak requested changes
Обрати внимание на это сообщение: https://github.com/mcrgnt/yp1/pull/5#pullrequestreview-2050139467

`golangci-lint` необходимо добавить в Github Actions

2024-05-16 11:13 UTC, s-shpak commented on internal/agent/agent.go
> +	metrics.ReportMetrics(&metrics.ReportMetricsParams{
Зачем делать этот вызов дополнительно ?

2024-05-16 11:13 UTC, s-shpak commented on internal/server/server.go
> +	go func() {
Пожалуйста, не исполльзуй горутины пока, ты неправильно работаешь с WaitGroup здесь

2024-05-16 11:13 UTC, s-shpak commented on internal/metrics/generate.go
> +func main() {
Это помещается в `cmd`, сделай это просто небольшой утилитой

2024-05-16 12:01 UTC, mcrgnt commented on internal/server/server.go
> +	go func() {
а что тут неправильно?

2024-05-16 12:03 UTC, mcrgnt commented on internal/agent/agent.go
> +	metrics.ReportMetrics(&metrics.ReportMetricsParams{
потому что тикер в первый раз срабатывает по истечении заданного времени

2024-05-16 12:46 UTC, mcrgnt commented on internal/metrics/metrics.go
> +		PollMetricsInc.Add(1)
ok

2024-05-16 12:46 UTC, mcrgnt commented on internal/agent/agent.go
> +	metrics.ReportMetrics(&metrics.ReportMetricsParams{
fixed

2024-05-16 12:46 UTC, mcrgnt commented on internal/server/server.go
> +	go func() {
fixed

2024-05-16 12:46 UTC, mcrgnt commented on internal/metrics/generate.go
> +func main() {
ok

2024-05-16 15:35 UTC, s-shpak requested changes

2024-05-16 15:35 UTC, s-shpak commented on internal/server/server.go
> +	go func() {
Я пока не понимаю, зачем ты это делаешь. Если это graceful shutdown, то он реализован неправильно. Я еще раз прошу тебя не добавлять горутины, потому что мы пока не разобрали, как работать с ними корректно.

Если ты все же хочешь это сделать, то, пожалуйста, почитай как, и сделай правильно (см. метод `Shutdown`)

2024-05-16 15:35 UTC, s-shpak commented on internal/agent/agent.go
> -	metrics.PollMetrics(&metrics.PollMetricsParams{
Собрать метрики один раз, в начале выполнения этой функции можно: чтобы точно гаранитровать, что отправление произойдет после хотя бы одного сбора

2024-05-16 15:35 UTC, s-shpak commented on internal/reporter/reporter.go
> +	_, _ = reporter.report(params)
Ошибки нельзя игнорировать, см. видео про обработку ошибок: https://app.pachca.com/chats/9180496?message=234290731

2024-05-16 15:35 UTC, s-shpak commented on internal/api/handler.go
> +	_, _ = fmt.Fprintf(w, "%s", value)
Численные значения необходимо кнвертировать при помощи пакета `strconv`

2024-05-16 15:35 UTC, s-shpak commented on internal/storage/memory.go
> +		data += fmt.Sprintf("%s: %v\r\n", k, v)
`strconv`

2024-05-16 15:56 UTC, mcrgnt commented on internal/agent/agent.go
> -	metrics.PollMetrics(&metrics.PollMetricsParams{
добавил

2024-05-16 15:58 UTC, mcrgnt commented on internal/api/handler.go
> +	_, _ = fmt.Fprintf(w, "%s", value)
тут уже не число а строка

2024-05-17 01:25 UTC, mcrgnt commented on internal/storage/memory.go
> +		data += fmt.Sprintf("%s: %v\r\n", k, v)
ok

2024-05-17 01:26 UTC, mcrgnt commented on internal/api/handler.go
> +	_, _ = fmt.Fprintf(w, "%s", value)
ok

2024-05-17 01:26 UTC, mcrgnt commented on internal/reporter/reporter.go
> +	_, _ = reporter.report(params)
not ignored

2024-05-17 05:30 UTC, mcrgnt commented
юнит тесты в процессе

2024-05-17 14:15 UTC, mcrgnt commented
Хотелось бы узнать как в юнит тестах тестировать flag.Parse()

2024-05-21 08:14 UTC, s-shpak approved these changes

2024-05-21 08:19 UTC, merged