Iter9
mcrgnt/yp1 pull request #9
Opened 2024-06-21 23:36 UTC by mcrgnt

2024-06-25 16:01 UTC, s-shpak requested changes
Избавься, пожалуйста, от всех:
1. `fmt.Print*`
2. ненужных `else`

2024-06-25 16:01 UTC, s-shpak commented on internal/api/handler_root.go
> +	_, _ = w.Write([]byte(htmlHeader + t.storage.GetMetricAll() + htmlFooter))
Ошибку лучше залогировать

2024-06-25 20:10 UTC, mcrgnt commented on internal/common/func.go
> +func CheckContentEncodingGZIP(r *http.Request) bool {
перенес и сдублировал

2024-06-25 20:10 UTC, mcrgnt commented on internal/api/handler.go
> +		// r.Use(handler.middlewareLogger)
почистил

2024-06-25 20:10 UTC, mcrgnt commented on internal/api/handler_update.go
> +	common.CheckAcceptEncodingGZIP(w, r)
перенес

2024-06-25 20:12 UTC, mcrgnt commented on internal/reporter/reporter.go
> +		} else {
не понял, но заменил на else if

2024-06-25 20:14 UTC, mcrgnt commented on internal/reporter/reporter.go
> +			} else {
не понимаю
![image](https://github.com/mcrgnt/yp1/assets/24764778/ed9331b4-c9e1-44a4-87c3-f788626dd32e)

2024-06-25 20:22 UTC, mcrgnt commented on internal/reporter/reporter.go
> +						fmt.Println(err)
готово

2024-06-25 20:25 UTC, mcrgnt commented on internal/filer/filer.go
> +func (t *Filer) Read() {
и что делать если там ошибка остановить работу сервиса?

2024-06-25 20:26 UTC, mcrgnt commented on internal/api/handler_root.go
> +	_, _ = w.Write([]byte(htmlHeader + t.storage.GetMetricAll() + htmlFooter))
залогировал

2024-06-25 20:30 UTC, mcrgnt commented on internal/api/handler.go
> +	handler.R.Group(func(r chi.Router) {
сгруппировал

2024-06-30 00:17 UTC, s-shpak commented on internal/reporter/reporter.go
> +		} else {
Проверь ошибку, выйди в случае `err != nil`, дальше продолжай выполнение кода не в блоке. Это сделает код более плоским

2024-06-30 00:17 UTC, s-shpak commented on internal/reporter/reporter.go
> +			} else {
`resp` не надо объявлять внутри блока if, т.к. тогда его областью видимости будет блок `if`

2024-06-30 00:21 UTC, s-shpak commented on internal/agent/api/handler.go
> +		r.Use(middleware.Logger, middleware.Compress(compressLevel, contentTypeToCompressList...))
Логгер должен использоваться в каждом эндпоинте, потому не надо объявлять его использование в каждой группе, объяви его для корневого роутера

2024-06-30 00:21 UTC, s-shpak commented on internal/filer/filer.go
> +func (t *Filer) Read() {
Да, если файл не получается прочитать при инициализации стора, то, наверное, логично будет остановить сервис полностью. В ином случае (например, при работе хендлера) можно было бы пробросить ошибку наверх, до сло транспорта, и там обработать (залогировать/отдать ошибку клиенту)

2024-06-30 00:22 UTC, s-shpak requested changes
См. комментарии

2024-06-30 00:31 UTC, mcrgnt commented on internal/reporter/reporter.go
> +		} else {
и добавит кучу объявления переменных var (...), сделано

2024-06-30 00:31 UTC, mcrgnt commented on internal/filer/filer.go
> +func (t *Filer) Read() {
логирует выше

2024-06-30 00:46 UTC, mcrgnt commented on internal/reporter/reporter.go
> +			} else {
да я это понимаю

2024-06-30 00:48 UTC, mcrgnt commented on internal/agent/api/handler.go
> +		r.Use(middleware.Logger, middleware.Compress(compressLevel, contentTypeToCompressList...))
готово

2024-06-30 00:50 UTC, mcrgnt commented
не могу ответить тут 
![image](https://github.com/mcrgnt/yp1/assets/24764778/aa57d38e-a5a3-42d8-8c39-c4b51dd91127)
уже пофикшено

2024-06-30 11:32 UTC, s-shpak commented on internal/filer/filer.go
> +func (t *Filer) Read() {
А что поменялось ?

2024-07-02 13:47 UTC, mcrgnt commented
@s-shpak thx

2024-07-02 13:47 UTC, merged